---

spring:
  application:
    name: boot-ads
  output:
    ansi:
      enabled: detect
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ads_development?useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 10000
      maximum-pool-size: 2
      minimum-idle: 2
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
  #        ddl-auto: create
  jackson:
    serialization:
      INDENT_OUTPUT: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true

  devtools:
    restart:
      enabled: true
#      exclude: "static/**, public/**"
#      additional-exclude: "**/*.xml"
#      additional-paths: ['src/main/resources/sql']
#      trigger-file: .reload

ads:
  env: development

server:
  port: 8080
  addr: localhost

admin:
  html: //localhost:8000
  fqdn: http://localhost:8000
  port: 8080
  scheme: http
  addr: localhost

#logging.file: demo.log
#logging:
#  file:
#    max-size: 50MB
#    max-history: 10
#  level:
#    root: info
#    org.springframework: info
#    org.hibernate: info
#    org.hibernate.SQL: debug
#    com.example.demo: debug
#
